const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '1'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "null" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_11_09_07_03_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjE2LFxuICAgICAgICAxMTEsXG4gICAgICAgIDExNCxcbiAgICAgICAgMTU0LFxuICAgICAgICA0MixcbiAgICAgICAgMTQsXG4gICAgICAgIDE2LFxuICAgICAgICA5MixcbiAgICAgICAgMTkzLFxuICAgICAgICAyMzUsXG4gICAgICAgIDEwMCxcbiAgICAgICAgMTk0LFxuICAgICAgICA1NSxcbiAgICAgICAgODEsXG4gICAgICAgIDU0LFxuICAgICAgICA2NSxcbiAgICAgICAgMTM3LFxuICAgICAgICAyMjIsXG4gICAgICAgIDUxLFxuICAgICAgICA0NyxcbiAgICAgICAgMjI0LFxuICAgICAgICAyMzYsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMTgyLFxuICAgICAgICAxMjMsXG4gICAgICAgIDc2LFxuICAgICAgICA3NixcbiAgICAgICAgMSxcbiAgICAgICAgNDYsXG4gICAgICAgIDI1LFxuICAgICAgICAyNSxcbiAgICAgICAgOTVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjA1LFxuICAgICAgICAzOSxcbiAgICAgICAgNDIsXG4gICAgICAgIDEyMixcbiAgICAgICAgMTM3LFxuICAgICAgICAyMTcsXG4gICAgICAgIDIxNixcbiAgICAgICAgMjQwLFxuICAgICAgICAyMjgsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMTEsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMTI3LFxuICAgICAgICAxMTgsXG4gICAgICAgIDUwLFxuICAgICAgICA1NyxcbiAgICAgICAgMjU0LFxuICAgICAgICAxNTQsXG4gICAgICAgIDE4MixcbiAgICAgICAgMTEwLFxuICAgICAgICAxNjIsXG4gICAgICAgIDExMixcbiAgICAgICAgNjEsXG4gICAgICAgIDEyNyxcbiAgICAgICAgNCxcbiAgICAgICAgMTU3LFxuICAgICAgICAyNyxcbiAgICAgICAgNzMsXG4gICAgICAgIDQ5LFxuICAgICAgICAyMTksXG4gICAgICAgIDI1LFxuICAgICAgICA3MFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTYwLFxuICAgICAgICAyMixcbiAgICAgICAgNDAsXG4gICAgICAgIDI2LFxuICAgICAgICAxNzIsXG4gICAgICAgIDExLFxuICAgICAgICAxNDYsXG4gICAgICAgIDIwOSxcbiAgICAgICAgMTcxLFxuICAgICAgICAxMzksXG4gICAgICAgIDgyLFxuICAgICAgICAyNTUsXG4gICAgICAgIDcwLFxuICAgICAgICA1NSxcbiAgICAgICAgMTMzLFxuICAgICAgICA3LFxuICAgICAgICAyNDcsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMTEzLFxuICAgICAgICAxMzYsXG4gICAgICAgIDMyLFxuICAgICAgICAxNDYsXG4gICAgICAgIDcwLFxuICAgICAgICA5NyxcbiAgICAgICAgMTcxLFxuICAgICAgICAyNDAsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTMsXG4gICAgICAgIDI1MyxcbiAgICAgICAgNDMsXG4gICAgICAgIDE3OCxcbiAgICAgICAgOTFcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgOTEsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMjM5LFxuICAgICAgICA2MixcbiAgICAgICAgMTksXG4gICAgICAgIDIxOCxcbiAgICAgICAgMTE2LFxuICAgICAgICAxMTksXG4gICAgICAgIDEzNyxcbiAgICAgICAgNixcbiAgICAgICAgMjM3LFxuICAgICAgICA3NixcbiAgICAgICAgNjIsXG4gICAgICAgIDY5LFxuICAgICAgICAxNDMsXG4gICAgICAgIDEyMCxcbiAgICAgICAgMjcsXG4gICAgICAgIDI1NCxcbiAgICAgICAgNDgsXG4gICAgICAgIDU1LFxuICAgICAgICAzNixcbiAgICAgICAgMjksXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTIwLFxuICAgICAgICAxNjYsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMjMwLFxuICAgICAgICAxNTEsXG4gICAgICAgIDE3NixcbiAgICAgICAgMjYsXG4gICAgICAgIDExNSxcbiAgICAgICAgMzRcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEzNixcbiAgICAgICAgMjAxLFxuICAgICAgICAyNDAsXG4gICAgICAgIDI0NSxcbiAgICAgICAgOTMsXG4gICAgICAgIDY3LFxuICAgICAgICA4NSxcbiAgICAgICAgMjQ1LFxuICAgICAgICA0MyxcbiAgICAgICAgMjA1LFxuICAgICAgICAxMDUsXG4gICAgICAgIDE5MCxcbiAgICAgICAgMyxcbiAgICAgICAgMTY1LFxuICAgICAgICA1MyxcbiAgICAgICAgMjQwLFxuICAgICAgICAxNjQsXG4gICAgICAgIDE4MCxcbiAgICAgICAgMjE3LFxuICAgICAgICAxNDEsXG4gICAgICAgIDYwLFxuICAgICAgICA5LFxuICAgICAgICAxNzEsXG4gICAgICAgIDE5MyxcbiAgICAgICAgOTYsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMjQ5LFxuICAgICAgICA4MixcbiAgICAgICAgMjEyLFxuICAgICAgICAxNjcsXG4gICAgICAgIDE4OSxcbiAgICAgICAgOTVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTY4LFxuICAgICAgICAxMDMsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMjI4LFxuICAgICAgICA2LFxuICAgICAgICAyMTcsXG4gICAgICAgIDI0MyxcbiAgICAgICAgNzIsXG4gICAgICAgIDE4MyxcbiAgICAgICAgMTE2LFxuICAgICAgICAxMSxcbiAgICAgICAgNjMsXG4gICAgICAgIDMzLFxuICAgICAgICAxMTMsXG4gICAgICAgIDY5LFxuICAgICAgICAxMTksXG4gICAgICAgIDExNixcbiAgICAgICAgMTIzLFxuICAgICAgICAxMjAsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTEsXG4gICAgICAgIDIwMyxcbiAgICAgICAgMjAxLFxuICAgICAgICAxODEsXG4gICAgICAgIDU3LFxuICAgICAgICAxMTUsXG4gICAgICAgIDExNCxcbiAgICAgICAgMTIxLFxuICAgICAgICAyMDUsXG4gICAgICAgIDE1LFxuICAgICAgICAxNjMsXG4gICAgICAgIDI3XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZFByZUtleVwiOiB7XG4gICAgXCJrZXlQYWlyXCI6IHtcbiAgICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDIxNixcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDI5LFxuICAgICAgICAgIDM0LFxuICAgICAgICAgIDIxNSxcbiAgICAgICAgICA4MCxcbiAgICAgICAgICAxMTAsXG4gICAgICAgICAgMzEsXG4gICAgICAgICAgMjIsXG4gICAgICAgICAgMTY5LFxuICAgICAgICAgIDE5NSxcbiAgICAgICAgICAyNTIsXG4gICAgICAgICAgMjQwLFxuICAgICAgICAgIDE3OCxcbiAgICAgICAgICA5MCxcbiAgICAgICAgICAxNzgsXG4gICAgICAgICAgMTUwLFxuICAgICAgICAgIDk2LFxuICAgICAgICAgIDIxNixcbiAgICAgICAgICAxNzksXG4gICAgICAgICAgMTAxLFxuICAgICAgICAgIDI0NixcbiAgICAgICAgICAxODAsXG4gICAgICAgICAgNTgsXG4gICAgICAgICAgMjAyLFxuICAgICAgICAgIDI1LFxuICAgICAgICAgIDQyLFxuICAgICAgICAgIDM4LFxuICAgICAgICAgIDI1NSxcbiAgICAgICAgICA4OCxcbiAgICAgICAgICA4MlxuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNDEsXG4gICAgICAgICAgODMsXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgOTEsXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAyLFxuICAgICAgICAgIDExMCxcbiAgICAgICAgICA4OSxcbiAgICAgICAgICAyMDksXG4gICAgICAgICAgMjgsXG4gICAgICAgICAgMTM2LFxuICAgICAgICAgIDYzLFxuICAgICAgICAgIDEzNixcbiAgICAgICAgICAxNTMsXG4gICAgICAgICAgOCxcbiAgICAgICAgICAyMzIsXG4gICAgICAgICAgNzcsXG4gICAgICAgICAgMjM5LFxuICAgICAgICAgIDE5NSxcbiAgICAgICAgICAxNDIsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDc2LFxuICAgICAgICAgIDE2MSxcbiAgICAgICAgICAxNzQsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDE4OCxcbiAgICAgICAgICAxMzUsXG4gICAgICAgICAgNjEsXG4gICAgICAgICAgMTU3LFxuICAgICAgICAgIDg1LFxuICAgICAgICAgIDEwM1xuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDQ1LFxuICAgICAgICA3NyxcbiAgICAgICAgOTQsXG4gICAgICAgIDE2NixcbiAgICAgICAgMTkyLFxuICAgICAgICAxNTEsXG4gICAgICAgIDQxLFxuICAgICAgICAzLFxuICAgICAgICAxNTEsXG4gICAgICAgIDg3LFxuICAgICAgICAzOCxcbiAgICAgICAgMTIyLFxuICAgICAgICAxMDAsXG4gICAgICAgIDIwNCxcbiAgICAgICAgMTc0LFxuICAgICAgICAxMTMsXG4gICAgICAgIDU4LFxuICAgICAgICA1OCxcbiAgICAgICAgMjA5LFxuICAgICAgICAxNDIsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMTUsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMTc2LFxuICAgICAgICAxNjEsXG4gICAgICAgIDExMSxcbiAgICAgICAgMjE3LFxuICAgICAgICAyNTEsXG4gICAgICAgIDExLFxuICAgICAgICA4NSxcbiAgICAgICAgMTUzLFxuICAgICAgICAxOTAsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTI0LFxuICAgICAgICAxMjksXG4gICAgICAgIDEyMyxcbiAgICAgICAgODksXG4gICAgICAgIDE0MixcbiAgICAgICAgMzksXG4gICAgICAgIDIyOCxcbiAgICAgICAgMjA3LFxuICAgICAgICAxMjgsXG4gICAgICAgIDMyLFxuICAgICAgICAyNixcbiAgICAgICAgMTY2LFxuICAgICAgICAyLFxuICAgICAgICA0MyxcbiAgICAgICAgMzcsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMTIzLFxuICAgICAgICA3OCxcbiAgICAgICAgMjEwLFxuICAgICAgICAxOTEsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMTYxLFxuICAgICAgICAxMjIsXG4gICAgICAgIDEyNCxcbiAgICAgICAgNyxcbiAgICAgICAgNzEsXG4gICAgICAgIDc2LFxuICAgICAgICA3LFxuICAgICAgICAxMjUsXG4gICAgICAgIDYsXG4gICAgICAgIDJcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDExMSxcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJSQUVKRFAveCtQYlJRUy8yYzdwZmwwQ21kRVEwVWFjdFdtd0hzT3MwUmpnPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjk0NzUxMjU3MjAwQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI1MzkyMUVBRURERUQ0QjQ5NkE5NTNENzI3RkQyREM4MlwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjAwMDQ5ODVcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5NDc1MTI1NzIwMEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiNjE4NUE1RjNEN0VDNzRFQzA2RTE1REYzREE1M0Q1QUNcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzIwMDA0OTg1XG4gICAgfSxcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTQ3NTEyNTcyMDBAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIkQwNUJFQUFEOThFQkM2MEVFOEZCRjhFRDE2N0FDRUNDXCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyMDAwNDk4OFxuICAgIH0sXG4gICAge1xuICAgICAgXCJrZXlcIjoge1xuICAgICAgICBcInJlbW90ZUppZFwiOiBcIjk0NzUxMjU3MjAwQHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCJBRDc1NkY4MDE4NkY1NzFBMzI2M0MzMDgzNDUwQjc3NFwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3MjAwMDQ5ODhcbiAgICB9XG4gIF0sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAxLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwibjVGZFd5aWJSdktEQmgxSDlacVJLZ1wiLFxuICBcInBob25lSWRcIjogXCIzZTkyODgzYS0zNjA4LTQ4MWQtYTU2Zi0yZmE0MzkzNDkwMWFcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTY1LFxuICAgICAgNjIsXG4gICAgICA2NyxcbiAgICAgIDEyMixcbiAgICAgIDIzMSxcbiAgICAgIDksXG4gICAgICAxMzEsXG4gICAgICA4NyxcbiAgICAgIDE1OCxcbiAgICAgIDk2LFxuICAgICAgMjM4LFxuICAgICAgMTcsXG4gICAgICAxNDcsXG4gICAgICAyMzAsXG4gICAgICA1MSxcbiAgICAgIDgyLFxuICAgICAgMzYsXG4gICAgICA0NixcbiAgICAgIDE4MCxcbiAgICAgIDc4XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogZmFsc2UsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA4NixcbiAgICAgIDE2NSxcbiAgICAgIDExLFxuICAgICAgMTAxLFxuICAgICAgMSxcbiAgICAgIDIyNyxcbiAgICAgIDIxOCxcbiAgICAgIDE4MyxcbiAgICAgIDAsXG4gICAgICAyNDEsXG4gICAgICAyNDUsXG4gICAgICAyMDIsXG4gICAgICA0MixcbiAgICAgIDIxMSxcbiAgICAgIDgwLFxuICAgICAgMjMzLFxuICAgICAgNDMsXG4gICAgICA1LFxuICAgICAgMjQyLFxuICAgICAgMTU3XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDSmIxL2ZjRUVQVGlsTFFHR0FFZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJ5Nm9hcUtwOVZsVnVqem1jRjNnWUhFU0hKRGl2eURpNEFjeDFDM1RYTFRvPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIjBHR0pBT2Robmx2NnFaNm9XUWJjTWNTekpCY1ZpclpobVlJR29JdjFyeGFxMEJzK1R4ZSt3WGlGeVA4a1krbGpDUzZmcE5ZcGQyQ0JvVWNEUEdmaEFRPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcInpYd2Mra3U1UExXOHIyT3NnMkhkTHZRdU1nSE5wdnpjek0wclcvaVlEa1pudEpYN3FCcnJCT3c5V0I1M2xseWI0WjluY25QRTVZQ0R1Ums5U3Y2SEF3PT1cIlxuICB9LFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiOTQ3NTEyNTcyMDA6OEBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibmFtZVwiOiBcIlNoYW4gQ3JlYXRpb25cIixcbiAgICBcImxpZFwiOiBcIjIyOTc0MzE2OTQ1NjQ2OjhAbGlkXCJcbiAgfSxcbiAgXCJzaWduYWxJZGVudGl0aWVzXCI6IFtcbiAgICB7XG4gICAgICBcImlkZW50aWZpZXJcIjoge1xuICAgICAgICBcIm5hbWVcIjogXCI5NDc1MTI1NzIwMDo4QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZGV2aWNlSWRcIjogMFxuICAgICAgfSxcbiAgICAgIFwiaWRlbnRpZmllcktleVwiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDUsXG4gICAgICAgICAgMjAzLFxuICAgICAgICAgIDE3MCxcbiAgICAgICAgICAyNixcbiAgICAgICAgICAxNjgsXG4gICAgICAgICAgMTcwLFxuICAgICAgICAgIDEyNSxcbiAgICAgICAgICA4NixcbiAgICAgICAgICA4NSxcbiAgICAgICAgICAxMTAsXG4gICAgICAgICAgMTQzLFxuICAgICAgICAgIDU3LFxuICAgICAgICAgIDE1NixcbiAgICAgICAgICAyMyxcbiAgICAgICAgICAxMjAsXG4gICAgICAgICAgMjQsXG4gICAgICAgICAgMjgsXG4gICAgICAgICAgNjgsXG4gICAgICAgICAgMTM1LFxuICAgICAgICAgIDM2LFxuICAgICAgICAgIDU2LFxuICAgICAgICAgIDE3NSxcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgNTYsXG4gICAgICAgICAgMTg0LFxuICAgICAgICAgIDEsXG4gICAgICAgICAgMjA0LFxuICAgICAgICAgIDExNyxcbiAgICAgICAgICAxMSxcbiAgICAgICAgICAxMTYsXG4gICAgICAgICAgMjE1LFxuICAgICAgICAgIDQ1LFxuICAgICAgICAgIDU4XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjAwMDQ5ODMsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFIelZcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUh6Uy5qc29uIjogIntcImtleURhdGFcIjpcImVKM0YwWldqNFMrK0RkcGZVN2d4alkrS0M3cWJXMzVTZE1VcWJvN2NRUEU9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTMyNTM2NTkwNyxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBSHpULmpzb24iOiAie1wia2V5RGF0YVwiOlwiWllwMWdkTXorOCt5VVVPNTR0SElUQnhrelN1cEM1a2wyVzFzdldkY3ZORT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMzI1MzY1OTA3LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMF19LFwidGltZXN0YW1wXCI6XCIxNzIwMDA0MjAxNzUzXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBSHpVLmpzb24iOiAie1wia2V5RGF0YVwiOlwiOTRrUGIvSjBKS1g2TVhKc1F3R0lRNTA2NmhWUmxiTDR4d2pFVW84L1VnQT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMzI1MzY1OTA4LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMF19LFwidGltZXN0YW1wXCI6XCIxNzIwMDA0Nzc1NzY4XCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBSHpWLmpzb24iOiAie1wia2V5RGF0YVwiOlwiK0YvRnp6NXd2d0x6ZXJjRksrS09Oc0FydW12b3E5NGJXdVVkaDVSdzFsaz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMzI1MzY1OTEwLFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjAwMDQ5ODUzMjNcIn0iCn0="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.7",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "",
  packname: process.env.PACK_NAME || "",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
